try integrating optional stack support into the .travis configuration

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,56 +1,112 @@
-# NB: don't set `language: haskell` here
+# This file has been generated -- see https://github.com/hvr/multi-ghc-travis
+language: c
+sudo: false
 
-# See also https://github.com/hvr/multi-ghc-travis for more information
-env:
- # we have to use CABALVER=1.16 for GHC<7.6 as well, as there's
- # no package for earlier cabal versions in the PPA
- - GHCVER=7.4.2 CABALVER=1.16
- - GHCVER=7.6.3 CABALVER=1.16
- - GHCVER=7.8.4 CABALVER=1.18
- - GHCVER=7.10.1 CABALVER=1.22
- - GHCVER=head CABALVER=1.22
+cache:
+  directories:
+    - $HOME/.cabsnap
+    - $HOME/.cabal/packages
+    - $HOME/.stack
+
+before_cache:
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
 
 matrix:
-  allow_failures:
-   - env: GHCVER=head CABALVER=1.22
+  include:
+    - env: CABALVER=1.16 GHCVER=7.4.2 BUILD=cabal
+      compiler: ": #GHC 7.4.2"
+      addons: {apt: {packages: [cabal-install-1.16,ghc-7.4.2,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
 
-# Note: the distinction between `before_install` and `install` is not
-#       important.
+    - env: CABALVER=1.16 GHCVER=7.6.3 BUILD=cabal
+      compiler: ": #GHC 7.6.3"
+      addons: {apt: {packages: [cabal-install-1.16,ghc-7.6.3,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
+
+    - env: CABALVER=1.18 GHCVER=7.8.4 BUILD=cabal
+      compiler: ": #GHC 7.8.4"
+      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
+
+    - env: CABALVER=1.18 GHCVER=7.8.4 BUILD=stack STACK_YAML=stack-7.8.yaml
+      compiler: ": #GHC 7.8.4"
+      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
+
+    - env: CABALVER=1.22 GHCVER=7.10.1 BUILD=cabal
+      compiler: ": #GHC 7.10.1"
+      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.1,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
+
+    - env: CABALVER=1.18 GHCVER=7.10.1 BUILD=stack STACK_YAML=stack.yaml
+      compiler: ": #GHC 7.10.1"
+      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.1,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
+
+    - env: CABALVER=1.22 GHCVER=7.10.2 BUILD=cabal
+      compiler: ": #GHC 7.10.2"
+      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
+
 before_install:
- - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
- - travis_retry sudo apt-get update
- - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
- - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
- - cabal --version
+ - unset CC
+ - export HAPPYVER=1.19.5
+ - export ALEXVER=3.1.4
+ - mkdir -p ~/.cabal/bin
+ - export PATH=~/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/$HAPPYVER/bin:/opt/alex/$ALEXVER/bin:$PATH
+ - if [ "$BUILD" = "stack" ]; then
+     travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.2.0/stack-0.1.2.0-x86_64-linux.gz | gunzip > ~/.cabal/bin/stack;
+     chmod a+x ~/.cabal/bin/stack;
+   fi
 
 install:
- - travis_retry cabal update
- - cabal install --only-dependencies
- - travis_retry sudo apt-get -q -y install hlint || cabal install hlint
+ - cabal --version
+ - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
+ - if [ "$BUILD" = "cabal" ]; then
+     if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ];
+     then
+       zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz >
+            $HOME/.cabal/packages/hackage.haskell.org/00-index.tar;
+     fi;
+     travis_retry cabal update;
+     sed -i 's/^jobs:.*$/jobs: 2/' $HOME/.cabal/config;
+     cabal install --only-dependencies --enable-tests --enable-benchmarks --dry -v > installplan.txt;
+     sed -i -e '1,/^Resolving /d' installplan.txt; cat installplan.txt;
+     if diff -u installplan.txt $HOME/.cabsnap/installplan.txt; then
+       echo "cabal build-cache HIT";
+       rm -rfv .ghc;
+       cp -a $HOME/.cabsnap/ghc $HOME/.ghc;
+       cp -a $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin $HOME/.cabal/;
+     else
+       echo "cabal build-cache MISS";
+       rm -rf $HOME/.cabsnap;
+       mkdir -p $HOME/.ghc $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin;
+       cabal install --only-dependencies --enable-tests --enable-benchmarks;
+       if [ "$GHCVER" = "7.10.1" ]; then cabal install Cabal-1.22.4.0; fi;
+     fi;
+     if [ ! -d $HOME/.cabsnap ]; then
+       echo "snapshotting package-db to build-cache";
+       mkdir $HOME/.cabsnap;
+       cp -a $HOME/.ghc $HOME/.cabsnap/ghc;
+       cp -a $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin installplan.txt $HOME/.cabsnap/;
+     fi;
+   fi
+ - if [ "$BUILD" = "stack" ]; then
+     ./travis_long stack --no-terminal --skip-ghc-check build --only-snapshot -j2;
+   fi
 
-# Here starts the actual work to be performed for the package under
-# test; any command which exits with a non-zero exit code causes the
-# build to fail.
+# snapshot package-db on cache miss
+
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
 script:
- # -v2 provides useful information for debugging
- - cabal configure -v2
-
- # this builds all libraries and executables
- # (including tests/benchmarks)
- - cabal build
-
- # tests that a source-distribution can be generated
- - cabal sdist
- - hlint src --cpp-define HLINT
-
- # check that the generated source-distribution can be built & installed
- - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
-   cd dist/;
-   if [ -f "$SRC_TGZ" ]; then
-      cabal install --force-reinstalls "$SRC_TGZ";
-   else
-      echo "expected '$SRC_TGZ' not found";
-      exit 1;
+ - if [ "$BUILD" = "cabal" ]; then
+     cabal configure --enable-tests -v2;  # -v2 provides useful information for debugging
+     cabal build;   # this builds all libraries and executables (including tests)
+     cabal test;
+     cabal bench || true;  # expected result: these will crash
+     cabal sdist || true;  # tests that a source-distribution can be generated
+     # Check that the resulting source distribution can be built & installed.
+     # If there are no other `.tar.gz` files in `dist`, this can be even simpler:
+     # `cabal install --force-reinstalls dist/*-*.tar.gz`
+     SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz && (cd dist && cabal install --force-reinstalls "$SRC_TGZ");
+   fi
+ - if [ "$BUILD" = "stack" ]; then
+     ./travis_long stack --no-terminal --skip-ghc-check build
    fi
 
 notifications:
@@ -59,4 +115,5 @@ notifications:
       - "irc.freenode.org#haskell-lens"
     skip_join: true
     template:
-      - "\x0313tagged\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
+      - "\x0313tagged\x0f/\x0306%{branch}\x0f \x0314%{commit}\x0f %{message} \x0302\x1f%{build_url}\x0f"
+# EOF
